keycloak:
  server-url: http://localhost:8080
  realm: intelibank
  client-id: intelibank-auth
  username: admin
  password: admin
  client-secret: 65Ixa4g6ltH6yhRwpbxkiGjpinGkFL8n

kafka:
  topic:
    messageHub: message-hub

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/intelibank